version: '3.8'

services:
  bucket-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bucket_service
    ports:
      - "8001:3001"
    env_file:
      - .env
    volumes:
      - "../Bucket:/user/Bucket"
    command: npm run start